### ISSUE TITLE
Rendering Error

### ISSUE THREAD

**Issue by fnawratil** [NoobDevGame/Misana#1]
Tiles werden im Maprenderer nicht richtig dargestellt... Möglicherweise Verschiebung der TextureID?

**Comment by XYZLassi** [comment]
Also das ist kein Problem von dem Renderer, dein Editor lädt die Map auch falsch

**Comment by fnawratil** [comment]
:/

**Comment by XYZLassi** [comment]
Ich hatte auch gerade das Problem gehabt das wahrscheinlich das ConntentTool die Pngs umbenannt hat.

**Comment by XYZLassi** [comment]
Sry ich nehm alles Zurpck nach dem ändern der Datei macht dein Editor alles richtig

**Comment by fnawratil** [comment]
Ne, du hast recht, Editor zeigt auch irgendwas an...
Aber das lief gestern doch noch?

**Comment by fnawratil** [comment]
Ein Problem gefunden: Aus irgendeinem Grund sind Indoor und Outdoor Tilesheet die gleiche Datei wie Dungeon?!

Ist irgendwie bei meinem letzten Commit passiert... :/

**Comment by XYZLassi** [comment]
Das Problem mit den gleichen Datein kommt von dem Contenttool

**Comment by fnawratil** [comment]
Aber warum?

**Comment by fnawratil** [comment]
Noch was anderes diesbezüglich: Momentan werden nur kompilierte Tilesheets geladen... Ist eigentlich Schwachsinn, weil es ja gut wäre die je nach Bedarf dynamisch zu laden, bzw. eventuell vom Server übertragen zu lassen.

**Comment by jvbsl** [comment]
Lasst mich doch schlafen...
Ich dacht ich bin kein Mitglied des Projekts? :P

**Comment by XYZLassi** [comment]
So weit kommt es noch.
Erst alles reformieren wollen und dann gehn ohne das es klappt.

Ich weiß jetzt das der Offset ab der 2 Texture kommt und abhängig von der Y-Position des Tiles ist.

**Comment by jvbsl** [comment]
1. hab ich nur alles von rave und Sebastian reklamiert und
2. als ich ging hat noch alles funktioniert

Und ich hab keine Ahnung was du meinst

**Comment by XYZLassi** [comment]
Dann hol dir develop und schon ob die Karte Map rendert ^^

**Comment by jvbsl** [comment]
Später :P

**Comment by fnawratil** [comment]
Du hast dich selbst ins Projekt eingebracht, selbst schuld :D
Außerdem steht neben deinem Namen doch klar "Member"

**Comment by jvbsl** [comment]
Nicht in dieses Projekt, da hab ich nur zugeguckt.
Außerdem um das nochmal klar zu stellen: Ich hab nichts falsch gemacht :P
